Feature/ubi 418 health
Ubivius/microservice-authentication pull request #9
Opened 2021-04-06 19:55 UTC by MaximeStOnge

#### What changes does this PR contain?
- Add liveness and readiness

#### Which JIRA ticket ID's are associated with this PR?
UBI-418

#### Does this PR change the outward facing API?
Yes

#### Additional comments and information

@ubivius/microservices

2021-04-09 12:59 UTC, ArcticWalrus requested changes

2021-04-09 12:59 UTC, ArcticWalrus commented on pkg/data/auth.go
> +const KeycloakPath = "http://keycloak:8080"
Should these be exported from the package?

2021-04-13 19:29 UTC, ArcticWalrus approved these changes

2021-04-14 18:46 UTC, ysma500 approved these changes

2021-04-14 19:02 UTC, merged